Use FACULTAD
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE TRAER_USUARIOS
@id int = null
AS
BEGIN
	IF @ID IS NULL
		SELECT * FROM ProyectoLUG.Usuarios
	ELSE 
		SELECT * FROM ProyectoLUG.Usuarios WHERE idUsuario = @id
END
GO
